Shader "Hidden/CubeCopy" {
Properties {
 _MainTex ("Main", CUBE) = "" { }
 _Level ("Level", Float) = 0
}
SubShader { 
 LOD 200
 Tags { "RenderType"="Opaque" }
 Pass {
  Tags { "RenderType"="Opaque" }
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 16705
Program "vp" {
SubProgram "d3d9 " {
"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    dp4 o0.x, c0, v0
					    dp4 o0.y, c1, v0
					    dp4 o0.z, c2, v0
					    dp4 o0.w, c3, v0
					    mov o1, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
}
Program "fp" {
SubProgram "d3d9 " {
"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float _Level;
					//   samplerCUBE _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Level       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    dcl_texcoord_pp v0.xyz
					    dcl_cube s0
					    mov_pp r0.xyz, v0
					    mov_pp r0.w, c0.x
					    texldl oC0, r0, s0
					
					// approximately 4 instruction slots used (2 texture, 2 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					sample_l o0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[6].x
					ret 
					// Approximately 0 instruction slots used"
}
}
 }
}
SubShader { 
 LOD 200
 Tags { "RenderType"="Opaque" }
 Pass {
  Tags { "RenderType"="Opaque" }
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 110530
Program "vp" {
SubProgram "d3d9 " {
"!!DX9VertexSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_2_0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov oT0, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Vertex
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c1         cb0             0         4  ( FLT, FLT, FLT, FLT)
					//
					//
					// Runtime generated constant mappings:
					//
					// Target Reg                               Constant Description
					// ---------- --------------------------------------------------
					// c0                              Vertex Shader position offset
					//
					//
					// Level9 shader bytecode:
					//
					    vs_2_0
					    dcl_texcoord v0
					    dcl_texcoord2 v2
					    mul r0, v0.y, c2
					    mad r0, c1, v0.x, r0
					    mad r0, c3, v0.z, r0
					    mad r0, c4, v0.w, r0
					    mad oPos.xy, r0.w, c0, r0
					    mov oPos.zw, r0
					    mov oT0, v2
					
					// approximately 7 instruction slots used
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
}
Program "fp" {
SubProgram "d3d9 " {
"!!DX9PixelSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float _Level;
					//   samplerCUBE _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Level       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_2_0
					    dcl_pp t0.xyz
					    dcl_cube s0
					    mov_pp r0.xyz, t0
					    mov_pp r0.w, c0.x
					    texldb r0, r0, s0
					    mov oC0, r0
					
					// approximately 4 instruction slots used (1 texture, 3 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					sample_l o0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[6].x
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Pixel
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c0         cb0             6         1  ( FLT, FLT, FLT, FLT)
					//
					//
					// Sampler/Resource to DX9 shader sampler mappings:
					//
					// Target Sampler Source Sampler  Source Resource
					// -------------- --------------- ----------------
					// s0             s0              t0               
					//
					//
					// Level9 shader bytecode:
					//
					    ps_2_0
					    dcl_pp t0
					    dcl_cube s0
					    mov_pp r0.xyz, t0
					    mov_pp r0.w, c0.x
					    texldb r0, r0, s0
					    mov oC0, r0
					
					// approximately 4 instruction slots used (1 texture, 3 arithmetic)
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					sample_b o0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[6].x
					ret 
					// Approximately 0 instruction slots used"
}
}
 }
}
}