Shader "Hidden/CubeBlend" {
Properties {
[NoScaleOffset]  _TexA ("Cubemap", CUBE) = "grey" { }
[NoScaleOffset]  _TexB ("Cubemap", CUBE) = "grey" { }
 _value ("Value", Range(0,1)) = 0.5
}
SubShader { 
 Tags { "QUEUE"="Background" "RenderType"="Background" }
 Pass {
  Tags { "QUEUE"="Background" "RenderType"="Background" }
  ZTest Always
  ZWrite Off
  GpuProgramID 17682
Program "vp" {
SubProgram "d3d9 " {
"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xyz
					    dp4 o0.x, c0, v0
					    dp4 o0.y, c1, v0
					    dp4 o0.z, c2, v0
					    dp4 o0.w, c3, v0
					    mov o1.xyz, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyz, v1.xyzx
					ret 
					// Approximately 0 instruction slots used"
}
}
Program "fp" {
SubProgram "d3d9 " {
"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float _Level;
					//   samplerCUBE _TexA;
					//   float4 _TexA_HDR;
					//   samplerCUBE _TexB;
					//   float4 _TexB_HDR;
					//   float _value;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TexA_HDR    c0       1
					//   _TexB_HDR    c1       1
					//   _Level       c2       1
					//   _value       c3       1
					//   _TexA        s0       1
					//   _TexB        s1       1
					//
					
					    ps_3_0
					    def c4, 1, 0, 0, 0
					    dcl_texcoord_pp v0.xyz
					    dcl_cube s0
					    dcl_cube s1
					    mov_pp r0.xyz, v0
					    mov_pp r0.w, c2.x
					    texldl_pp r1, r0, s0
					    texldl_pp r0, r0, s1
					    pow_pp r2.x, r1.w, c0.y
					    mul_pp r1.w, r2.x, c0.x
					    mul_pp r1.xyz, r1, r1.w
					    pow_pp r1.w, r0.w, c1.y
					    mul_pp r0.w, r1.w, c1.x
					    mad r0.xyz, r0.w, r0, -r1
					    mad_pp oC0.xyz, c3.x, r0, r1
					    mov_pp oC0.w, c4.x
					
					// approximately 18 instruction slots used (4 texture, 14 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					sample_l r0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[8].x
					log r0.w, r0.w
					mul r0.w, r0.w, cb0[6].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb0[6].x
					mul r0.xyz, r0.xyzx, r0.wwww
					sample_l r1.xyzw, v1.xyzx, t1.xyzw, s1, cb0[8].x
					log r0.w, r1.w
					mul r0.w, r0.w, cb0[7].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb0[7].x
					mad r1.xyz, r0.wwww, r1.xyzx, -r0.xyzx
					mad o0.xyz, cb0[8].yyyy, r1.xyzx, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
}
}
 }
}
SubShader { 
 Tags { "QUEUE"="Background" "RenderType"="Background" }
 Pass {
  Tags { "QUEUE"="Background" "RenderType"="Background" }
  ZTest Always
  ZWrite Off
  GpuProgramID 113859
Program "vp" {
SubProgram "d3d9 " {
"!!DX9VertexSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_2_0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov oT0.xyz, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyz, v1.xyzx
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Vertex
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c1         cb0             0         4  ( FLT, FLT, FLT, FLT)
					//
					//
					// Runtime generated constant mappings:
					//
					// Target Reg                               Constant Description
					// ---------- --------------------------------------------------
					// c0                              Vertex Shader position offset
					//
					//
					// Level9 shader bytecode:
					//
					    vs_2_0
					    dcl_texcoord v0
					    dcl_texcoord1 v1
					    mul r0, v0.y, c2
					    mad r0, c1, v0.x, r0
					    mad r0, c3, v0.z, r0
					    mad r0, c4, v0.w, r0
					    mad oPos.xy, r0.w, c0, r0
					    mov oPos.zw, r0
					    mov oT0.xyz, v1
					
					// approximately 7 instruction slots used
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xyz, v1.xyzx
					ret 
					// Approximately 0 instruction slots used"
}
}
Program "fp" {
SubProgram "d3d9 " {
"!!DX9PixelSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float _Level;
					//   samplerCUBE _TexA;
					//   float4 _TexA_HDR;
					//   samplerCUBE _TexB;
					//   float4 _TexB_HDR;
					//   float _value;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TexA_HDR    c0       1
					//   _TexB_HDR    c1       1
					//   _Level       c2       1
					//   _value       c3       1
					//   _TexA        s0       1
					//   _TexB        s1       1
					//
					
					    ps_2_0
					    def c4, 1, 0, 0, 0
					    dcl_pp t0.xyz
					    dcl_cube s0
					    dcl_cube s1
					    mov_pp r0.xyz, t0
					    mov_pp r0.w, c2.x
					    texldb_pp r1, r0, s0
					    texldb_pp r0, r0, s1
					    pow_pp r2.w, r1.w, c0.y
					    mul_pp r1.w, r2.w, c0.x
					    mul_pp r1.xyz, r1, r1.w
					    pow_pp r1.w, r0.w, c1.y
					    mul_pp r0.w, r1.w, c1.x
					    mad r0.xyz, r0.w, r0, -r1
					    mad_pp r0.xyz, c3.x, r0, r1
					    mov_pp r0.w, c4.x
					    mov_pp oC0, r0
					
					// approximately 17 instruction slots used (2 texture, 15 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					sample_l r0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[8].x
					log r0.w, r0.w
					mul r0.w, r0.w, cb0[6].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb0[6].x
					mul r0.xyz, r0.xyzx, r0.wwww
					sample_l r1.xyzw, v1.xyzx, t1.xyzw, s1, cb0[8].x
					log r0.w, r1.w
					mul r0.w, r0.w, cb0[7].y
					exp r0.w, r0.w
					mul r0.w, r0.w, cb0[7].x
					mad r1.xyz, r0.wwww, r1.xyzx, -r0.xyzx
					mad o0.xyz, cb0[8].yyyy, r1.xyzx, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Pixel
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyz         1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c0         cb0             6         3  ( FLT, FLT, FLT, FLT)
					//
					//
					// Sampler/Resource to DX9 shader sampler mappings:
					//
					// Target Sampler Source Sampler  Source Resource
					// -------------- --------------- ----------------
					// s0             s0              t0               
					// s1             s1              t1               
					//
					//
					// Level9 shader bytecode:
					//
					    ps_2_0
					    def c3, 1, 0, 0, 0
					    dcl_pp t0.xyz
					    dcl_cube s0
					    dcl_cube s1
					    mov_pp r0.xyz, t0
					    mov_pp r0.w, c2.x
					    texldb_pp r1, r0, s0
					    texldb_pp r0, r0, s1
					    mul_pp r1.w, r1.w, c0.x
					    mul_pp r1.xyz, r1, r1.w
					    mul_pp r0.w, r0.w, c1.x
					    mad r0.xyz, r0.w, r0, -r1
					    mad_pp r0.xyz, c2.y, r0, r1
					    mov_pp r0.w, c3.x
					    mov_pp oC0, r0
					
					// approximately 11 instruction slots used (2 texture, 9 arithmetic)
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texturecube (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					sample_b r0.xyzw, v1.xyzx, t0.xyzw, s0, cb0[8].x
					mul r0.w, r0.w, cb0[6].x
					mul r0.xyz, r0.xyzx, r0.wwww
					sample_b r1.xyzw, v1.xyzx, t1.xyzw, s1, cb0[8].x
					mul r0.w, r1.w, cb0[7].x
					mad r1.xyz, r0.wwww, r1.xyzx, -r0.xyzx
					mad o0.xyz, cb0[8].yyyy, r1.xyzx, r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
}
}
 }
}
Fallback Off
}