Shader "Hidden/InternalSplashShadowBlur" {
SubShader { 
 Pass {
  ZTest Always
  Cull Off
  GpuProgramID 58662
Program "vp" {
SubProgram "opengl " {
"!!GLLegacy
					#version 120
					
					#ifdef VERTEX
					
					varying vec2 xlv_TEXCOORD0;
					void main ()
					{
					  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
					  xlv_TEXCOORD0 = gl_MultiTexCoord0.xy;
					}
					
					
					#endif
					#ifdef FRAGMENT
					uniform sampler2D _MainTex;
					uniform vec4 _MainTex_TexelSize;
					varying vec2 xlv_TEXCOORD0;
					void main ()
					{
					  vec2 tmpvar_1;
					  tmpvar_1.y = 0.0;
					  tmpvar_1.x = (-2.25 * _MainTex_TexelSize.x);
					  vec2 tmpvar_2;
					  tmpvar_2.y = 0.0;
					  tmpvar_2.x = (-0.4473684 * _MainTex_TexelSize.x);
					  vec2 tmpvar_3;
					  tmpvar_3.y = 0.0;
					  tmpvar_3.x = (1.306122 * _MainTex_TexelSize.x);
					  vec2 tmpvar_4;
					  tmpvar_4.y = 0.0;
					  tmpvar_4.x = (3.0 * _MainTex_TexelSize.x);
					  gl_FragData[0] = (((
					    (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_1)) * 0.1333333)
					   + 
					    (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_2)) * 0.5066667)
					  ) + (texture2D (_MainTex, 
					    (xlv_TEXCOORD0 + tmpvar_3)
					  ) * 0.3266667)) + (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_4)) * 0.03333334));
					}
					
					
					#endif"
}
SubProgram "d3d9 " {
"!!DX9VertexSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_2_0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov oT0.xy, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles " {
"!!GLES
					#version 100
					
					#ifdef VERTEX
					attribute vec4 _glesVertex;
					attribute vec4 _glesMultiTexCoord0;
					uniform highp mat4 glstate_matrix_mvp;
					varying highp vec2 xlv_TEXCOORD0;
					void main ()
					{
					  gl_Position = (glstate_matrix_mvp * _glesVertex);
					  xlv_TEXCOORD0 = _glesMultiTexCoord0.xy;
					}
					
					
					#endif
					#ifdef FRAGMENT
					uniform sampler2D _MainTex;
					uniform highp vec4 _MainTex_TexelSize;
					varying highp vec2 xlv_TEXCOORD0;
					void main ()
					{
					  lowp vec4 tmpvar_1;
					  highp vec4 average_2;
					  highp vec2 tmpvar_3;
					  tmpvar_3.y = 0.0;
					  tmpvar_3.x = (-2.25 * _MainTex_TexelSize.x);
					  highp vec2 P_4;
					  P_4 = (xlv_TEXCOORD0 + tmpvar_3);
					  highp vec2 tmpvar_5;
					  tmpvar_5.y = 0.0;
					  tmpvar_5.x = (-0.4473684 * _MainTex_TexelSize.x);
					  highp vec2 P_6;
					  P_6 = (xlv_TEXCOORD0 + tmpvar_5);
					  highp vec2 tmpvar_7;
					  tmpvar_7.y = 0.0;
					  tmpvar_7.x = (1.306122 * _MainTex_TexelSize.x);
					  highp vec2 P_8;
					  P_8 = (xlv_TEXCOORD0 + tmpvar_7);
					  highp vec2 tmpvar_9;
					  tmpvar_9.y = 0.0;
					  tmpvar_9.x = (3.0 * _MainTex_TexelSize.x);
					  highp vec2 P_10;
					  P_10 = (xlv_TEXCOORD0 + tmpvar_9);
					  lowp vec4 tmpvar_11;
					  tmpvar_11 = (((
					    (texture2D (_MainTex, P_4) * 0.1333333)
					   + 
					    (texture2D (_MainTex, P_6) * 0.5066667)
					  ) + (texture2D (_MainTex, P_8) * 0.3266667)) + (texture2D (_MainTex, P_10) * 0.03333334));
					  average_2 = tmpvar_11;
					  tmpvar_1 = average_2;
					  gl_FragData[0] = tmpvar_1;
					}
					
					
					#endif"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Vertex
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c1         cb0             0         4  ( FLT, FLT, FLT, FLT)
					//
					//
					// Runtime generated constant mappings:
					//
					// Target Reg                               Constant Description
					// ---------- --------------------------------------------------
					// c0                              Vertex Shader position offset
					//
					//
					// Level9 shader bytecode:
					//
					    vs_2_0
					    dcl_texcoord v0
					    dcl_texcoord1 v1
					    mul r0, v0.y, c2
					    mad r0, c1, v0.x, r0
					    mad r0, c3, v0.z, r0
					    mad r0, c4, v0.w, r0
					    mad oPos.xy, r0.w, c0, r0
					    mov oPos.zw, r0
					    mov oT0.xy, v1
					
					// approximately 7 instruction slots used
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles3 " {
"!!GLES3
					#ifdef VERTEX
					#version 300 es
					precision highp float;
					precision highp int;
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	mediump vec4 unity_4LightAtten0;
					uniform 	mediump vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	mediump vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	mediump vec4 unity_SHAr;
					uniform 	mediump vec4 unity_SHAg;
					uniform 	mediump vec4 unity_SHAb;
					uniform 	mediump vec4 unity_SHBr;
					uniform 	mediump vec4 unity_SHBg;
					uniform 	mediump vec4 unity_SHBb;
					uniform 	mediump vec4 unity_SHC;
					uniform 	mediump vec3 unity_LightColor0;
					uniform 	mediump vec3 unity_LightColor1;
					uniform 	mediump vec3 unity_LightColor2;
					uniform 	mediump vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	mediump vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	lowp vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	lowp vec4 unity_AmbientSky;
					uniform 	lowp vec4 unity_AmbientEquator;
					uniform 	lowp vec4 unity_AmbientGround;
					uniform 	lowp vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					in highp vec4 in_POSITION0;
					in highp vec2 in_TEXCOORD0;
					out highp vec2 vs_TEXCOORD0;
					highp vec4 t0;
					void main()
					{
					    t0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    t0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + t0;
					    t0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + t0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + t0;
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    return;
					}
					#endif
					#ifdef FRAGMENT
					#version 300 es
					precision highp float;
					precision highp int;
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	mediump vec4 unity_4LightAtten0;
					uniform 	mediump vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	mediump vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	mediump vec4 unity_SHAr;
					uniform 	mediump vec4 unity_SHAg;
					uniform 	mediump vec4 unity_SHAb;
					uniform 	mediump vec4 unity_SHBr;
					uniform 	mediump vec4 unity_SHBg;
					uniform 	mediump vec4 unity_SHBb;
					uniform 	mediump vec4 unity_SHC;
					uniform 	mediump vec3 unity_LightColor0;
					uniform 	mediump vec3 unity_LightColor1;
					uniform 	mediump vec3 unity_LightColor2;
					uniform 	mediump vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	mediump vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	lowp vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	lowp vec4 unity_AmbientSky;
					uniform 	lowp vec4 unity_AmbientEquator;
					uniform 	lowp vec4 unity_AmbientGround;
					uniform 	lowp vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					uniform lowp sampler2D _MainTex;
					in highp vec2 vs_TEXCOORD0;
					layout(location = 0) out lowp vec4 SV_Target0;
					highp vec4 t0;
					lowp vec4 t10_0;
					highp vec4 t1;
					lowp vec4 t10_1;
					lowp vec4 t10_2;
					void main()
					{
					    t0.xz = _MainTex_TexelSize.xx * vec2(-2.25, -0.447368413);
					    t0.yw = vec2(0.0, 0.0);
					    t0 = t0 + vs_TEXCOORD0.xyxy;
					    t10_1 = texture(_MainTex, t0.zw);
					    t10_0 = texture(_MainTex, t0.xy);
					    t10_1 = t10_1 * vec4(0.50666666, 0.50666666, 0.50666666, 0.50666666);
					    t10_0 = t10_0 * vec4(0.13333334, 0.13333334, 0.13333334, 0.13333334) + t10_1;
					    t1.xz = _MainTex_TexelSize.xx * vec2(1.30612242, 3.0);
					    t1.yw = vec2(0.0, 0.0);
					    t1 = t1 + vs_TEXCOORD0.xyxy;
					    t10_2 = texture(_MainTex, t1.xy);
					    t10_1 = texture(_MainTex, t1.zw);
					    t10_0 = t10_2 * vec4(0.326666653, 0.326666653, 0.326666653, 0.326666653) + t10_0;
					    SV_Target0 = t10_1 * vec4(0.0333333351, 0.0333333351, 0.0333333351, 0.0333333351) + t10_0;
					    return;
					}
					#endif"
}
SubProgram "glcore " {
"!!GLCore32
					#ifdef VERTEX
					#version 150
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_shader_bit_encoding : enable
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	vec4 unity_4LightAtten0;
					uniform 	vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	vec4 unity_SHAr;
					uniform 	vec4 unity_SHAg;
					uniform 	vec4 unity_SHAb;
					uniform 	vec4 unity_SHBr;
					uniform 	vec4 unity_SHBg;
					uniform 	vec4 unity_SHBb;
					uniform 	vec4 unity_SHC;
					uniform 	vec3 unity_LightColor0;
					uniform 	vec3 unity_LightColor1;
					uniform 	vec3 unity_LightColor2;
					uniform 	vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	vec4 unity_AmbientSky;
					uniform 	vec4 unity_AmbientEquator;
					uniform 	vec4 unity_AmbientGround;
					uniform 	vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					vec4 t0;
					void main()
					{
					    t0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    t0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + t0;
					    t0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + t0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + t0;
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    return;
					}
					#endif
					#ifdef FRAGMENT
					#version 150
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_shader_bit_encoding : enable
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	vec4 unity_4LightAtten0;
					uniform 	vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	vec4 unity_SHAr;
					uniform 	vec4 unity_SHAg;
					uniform 	vec4 unity_SHAb;
					uniform 	vec4 unity_SHBr;
					uniform 	vec4 unity_SHBg;
					uniform 	vec4 unity_SHBb;
					uniform 	vec4 unity_SHC;
					uniform 	vec3 unity_LightColor0;
					uniform 	vec3 unity_LightColor1;
					uniform 	vec3 unity_LightColor2;
					uniform 	vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	vec4 unity_AmbientSky;
					uniform 	vec4 unity_AmbientEquator;
					uniform 	vec4 unity_AmbientGround;
					uniform 	vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 t0;
					mediump vec4 t16_0;
					lowp vec4 t10_0;
					vec4 t1;
					mediump vec4 t16_1;
					lowp vec4 t10_1;
					lowp vec4 t10_2;
					void main()
					{
					    t0.xz = _MainTex_TexelSize.xx * vec2(-2.25, -0.447368413);
					    t0.yw = vec2(0.0, 0.0);
					    t0 = t0 + vs_TEXCOORD0.xyxy;
					    t10_1 = texture(_MainTex, t0.zw);
					    t10_0 = texture(_MainTex, t0.xy);
					    t16_1 = t10_1 * vec4(0.50666666, 0.50666666, 0.50666666, 0.50666666);
					    t16_0 = t10_0 * vec4(0.13333334, 0.13333334, 0.13333334, 0.13333334) + t16_1;
					    t1.xz = _MainTex_TexelSize.xx * vec2(1.30612242, 3.0);
					    t1.yw = vec2(0.0, 0.0);
					    t1 = t1 + vs_TEXCOORD0.xyxy;
					    t10_2 = texture(_MainTex, t1.xy);
					    t10_1 = texture(_MainTex, t1.zw);
					    t16_0 = t10_2 * vec4(0.326666653, 0.326666653, 0.326666653, 0.326666653) + t16_0;
					    SV_Target0 = t10_1 * vec4(0.0333333351, 0.0333333351, 0.0333333351, 0.0333333351) + t16_0;
					    return;
					}
					#endif"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLLegacy"
}
SubProgram "d3d9 " {
"!!DX9PixelSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float4 _MainTex_TexelSize;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _MainTex_TexelSize c0       1
					//   _MainTex           s0       1
					//
					
					    ps_2_0
					    def c1, -2.25, 0, -0.447368413, 1.30612242
					    def c2, 3, 0.50666666, 0.13333334, 0.326666653
					    def c3, 0.0333333351, 0, 0, 0
					    dcl t0.xy
					    dcl_2d s0
					    mov r0.xzw, c1
					    mul r1.x, r0.z, c0.x
					    mov r1.y, c1.y
					    add r1.xy, r1, t0
					    mul r0.x, r0.x, c0.x
					    mov r0.y, c1.y
					    add r0.xy, r0, t0
					    mul r2.x, r0.w, c0.x
					    mov r2.y, c1.y
					    add r2.xy, r2, t0
					    mov r3.w, c2.x
					    mul r3.x, r3.w, c0.x
					    mov r3.y, c1.y
					    add r3.xy, r3, t0
					    texld_pp r1, r1, s0
					    texld_pp r0, r0, s0
					    texld_pp r2, r2, s0
					    texld_pp r3, r3, s0
					    mul_pp r1, r1, c2.y
					    mad_pp r0, r0, c2.z, r1
					    mad_pp r0, r2, c2.w, r0
					    mad_pp r0, r3, c3.x, r0
					    mov_pp oC0, r0
					
					// approximately 23 instruction slots used (4 texture, 19 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.xz, cb0[0].xxxx, l(-2.250000, 0.000000, -0.447368, 0.000000)
					mov r0.yw, l(0,0,0,0)
					add r0.xyzw, r0.xyzw, v1.xyxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r1.xyzw, r1.xyzw, l(0.506667, 0.506667, 0.506667, 0.506667)
					mad r0.xyzw, r0.xyzw, l(0.133333, 0.133333, 0.133333, 0.133333), r1.xyzw
					mul r1.xz, cb0[0].xxxx, l(1.306122, 0.000000, 3.000000, 0.000000)
					mov r1.yw, l(0,0,0,0)
					add r1.xyzw, r1.xyzw, v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.326667, 0.326667, 0.326667, 0.326667), r0.xyzw
					mad o0.xyzw, r1.xyzw, l(0.033333, 0.033333, 0.033333, 0.033333), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles " {
"!!GLES"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Pixel
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c0         cb0             0         1  ( FLT, FLT, FLT, FLT)
					//
					//
					// Sampler/Resource to DX9 shader sampler mappings:
					//
					// Target Sampler Source Sampler  Source Resource
					// -------------- --------------- ----------------
					// s0             s0              t0               
					//
					//
					// Level9 shader bytecode:
					//
					    ps_2_0
					    def c1, -2.25, 0, -0.447368413, 1.30612242
					    def c2, 3, 0.50666666, 0.13333334, 0.326666653
					    def c3, 0.0333333351, 0, 0, 0
					    dcl t0.xy
					    dcl_2d s0
					    mov r0.xzw, c1
					    mul r1.x, r0.z, c0.x
					    mov r1.y, c1.y
					    add r1.xy, r1, t0
					    mul r0.x, r0.x, c0.x
					    mov r0.y, c1.y
					    add r0.xy, r0, t0
					    mul r2.x, r0.w, c0.x
					    mov r2.y, c1.y
					    add r2.xy, r2, t0
					    mov r3.w, c2.x
					    mul r3.x, r3.w, c0.x
					    mov r3.y, c1.y
					    add r3.xy, r3, t0
					    texld_pp r1, r1, s0
					    texld_pp r0, r0, s0
					    texld_pp r2, r2, s0
					    texld_pp r3, r3, s0
					    mul_pp r1, r1, c2.y
					    mad_pp r0, r0, c2.z, r1
					    mad_pp r0, r2, c2.w, r0
					    mad_pp r0, r3, c3.x, r0
					    mov_pp oC0, r0
					
					// approximately 23 instruction slots used (4 texture, 19 arithmetic)
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.xz, cb0[0].xxxx, l(-2.250000, 0.000000, -0.447368, 0.000000)
					mov r0.yw, l(0,0,0,0)
					add r0.xyzw, r0.xyzw, v1.xyxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r1.xyzw, r1.xyzw, l(0.506667, 0.506667, 0.506667, 0.506667)
					mad r0.xyzw, r0.xyzw, l(0.133333, 0.133333, 0.133333, 0.133333), r1.xyzw
					mul r1.xz, cb0[0].xxxx, l(1.306122, 0.000000, 3.000000, 0.000000)
					mov r1.yw, l(0,0,0,0)
					add r1.xyzw, r1.xyzw, v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.326667, 0.326667, 0.326667, 0.326667), r0.xyzw
					mad o0.xyzw, r1.xyzw, l(0.033333, 0.033333, 0.033333, 0.033333), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles3 " {
"!!GLES3"
}
SubProgram "glcore " {
"!!GLCore32"
}
}
 }
 Pass {
  ZTest Always
  Cull Off
  GpuProgramID 130145
Program "vp" {
SubProgram "opengl " {
"!!GLLegacy
					#version 120
					
					#ifdef VERTEX
					
					varying vec2 xlv_TEXCOORD0;
					void main ()
					{
					  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
					  xlv_TEXCOORD0 = gl_MultiTexCoord0.xy;
					}
					
					
					#endif
					#ifdef FRAGMENT
					uniform sampler2D _MainTex;
					uniform vec4 _MainTex_TexelSize;
					varying vec2 xlv_TEXCOORD0;
					void main ()
					{
					  vec2 tmpvar_1;
					  tmpvar_1.x = 0.0;
					  tmpvar_1.y = (-2.25 * _MainTex_TexelSize.y);
					  vec2 tmpvar_2;
					  tmpvar_2.x = 0.0;
					  tmpvar_2.y = (-0.4473684 * _MainTex_TexelSize.y);
					  vec2 tmpvar_3;
					  tmpvar_3.x = 0.0;
					  tmpvar_3.y = (1.306122 * _MainTex_TexelSize.y);
					  vec2 tmpvar_4;
					  tmpvar_4.x = 0.0;
					  tmpvar_4.y = (3.0 * _MainTex_TexelSize.y);
					  gl_FragData[0] = (((
					    (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_1)) * 0.1333333)
					   + 
					    (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_2)) * 0.5066667)
					  ) + (texture2D (_MainTex, 
					    (xlv_TEXCOORD0 + tmpvar_3)
					  ) * 0.3266667)) + (texture2D (_MainTex, (xlv_TEXCOORD0 + tmpvar_4)) * 0.03333334));
					}
					
					
					#endif"
}
SubProgram "d3d9 " {
"!!DX9VertexSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_2_0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov oT0.xy, v1
					
					// approximately 5 instruction slots used"
}
SubProgram "d3d11 " {
"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles " {
"!!GLES
					#version 100
					
					#ifdef VERTEX
					attribute vec4 _glesVertex;
					attribute vec4 _glesMultiTexCoord0;
					uniform highp mat4 glstate_matrix_mvp;
					varying highp vec2 xlv_TEXCOORD0;
					void main ()
					{
					  gl_Position = (glstate_matrix_mvp * _glesVertex);
					  xlv_TEXCOORD0 = _glesMultiTexCoord0.xy;
					}
					
					
					#endif
					#ifdef FRAGMENT
					uniform sampler2D _MainTex;
					uniform highp vec4 _MainTex_TexelSize;
					varying highp vec2 xlv_TEXCOORD0;
					void main ()
					{
					  lowp vec4 tmpvar_1;
					  highp vec4 average_2;
					  highp vec2 tmpvar_3;
					  tmpvar_3.x = 0.0;
					  tmpvar_3.y = (-2.25 * _MainTex_TexelSize.y);
					  highp vec2 P_4;
					  P_4 = (xlv_TEXCOORD0 + tmpvar_3);
					  highp vec2 tmpvar_5;
					  tmpvar_5.x = 0.0;
					  tmpvar_5.y = (-0.4473684 * _MainTex_TexelSize.y);
					  highp vec2 P_6;
					  P_6 = (xlv_TEXCOORD0 + tmpvar_5);
					  highp vec2 tmpvar_7;
					  tmpvar_7.x = 0.0;
					  tmpvar_7.y = (1.306122 * _MainTex_TexelSize.y);
					  highp vec2 P_8;
					  P_8 = (xlv_TEXCOORD0 + tmpvar_7);
					  highp vec2 tmpvar_9;
					  tmpvar_9.x = 0.0;
					  tmpvar_9.y = (3.0 * _MainTex_TexelSize.y);
					  highp vec2 P_10;
					  P_10 = (xlv_TEXCOORD0 + tmpvar_9);
					  lowp vec4 tmpvar_11;
					  tmpvar_11 = (((
					    (texture2D (_MainTex, P_4) * 0.1333333)
					   + 
					    (texture2D (_MainTex, P_6) * 0.5066667)
					  ) + (texture2D (_MainTex, P_8) * 0.3266667)) + (texture2D (_MainTex, P_10) * 0.03333334));
					  average_2 = tmpvar_11;
					  tmpvar_1 = average_2;
					  gl_FragData[0] = tmpvar_1;
					}
					
					
					#endif"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Vertex
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c1         cb0             0         4  ( FLT, FLT, FLT, FLT)
					//
					//
					// Runtime generated constant mappings:
					//
					// Target Reg                               Constant Description
					// ---------- --------------------------------------------------
					// c0                              Vertex Shader position offset
					//
					//
					// Level9 shader bytecode:
					//
					    vs_2_0
					    dcl_texcoord v0
					    dcl_texcoord1 v1
					    mul r0, v0.y, c2
					    mad r0, c1, v0.x, r0
					    mad r0, c3, v0.z, r0
					    mad r0, c4, v0.w, r0
					    mad oPos.xy, r0.w, c0, r0
					    mov oPos.zw, r0
					    mov oT0.xy, v1
					
					// approximately 7 instruction slots used
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 1
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					mad o0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles3 " {
"!!GLES3
					#ifdef VERTEX
					#version 300 es
					precision highp float;
					precision highp int;
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	mediump vec4 unity_4LightAtten0;
					uniform 	mediump vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	mediump vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	mediump vec4 unity_SHAr;
					uniform 	mediump vec4 unity_SHAg;
					uniform 	mediump vec4 unity_SHAb;
					uniform 	mediump vec4 unity_SHBr;
					uniform 	mediump vec4 unity_SHBg;
					uniform 	mediump vec4 unity_SHBb;
					uniform 	mediump vec4 unity_SHC;
					uniform 	mediump vec3 unity_LightColor0;
					uniform 	mediump vec3 unity_LightColor1;
					uniform 	mediump vec3 unity_LightColor2;
					uniform 	mediump vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	mediump vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	lowp vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	lowp vec4 unity_AmbientSky;
					uniform 	lowp vec4 unity_AmbientEquator;
					uniform 	lowp vec4 unity_AmbientGround;
					uniform 	lowp vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					in highp vec4 in_POSITION0;
					in highp vec2 in_TEXCOORD0;
					out highp vec2 vs_TEXCOORD0;
					highp vec4 t0;
					void main()
					{
					    t0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    t0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + t0;
					    t0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + t0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + t0;
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    return;
					}
					#endif
					#ifdef FRAGMENT
					#version 300 es
					precision highp float;
					precision highp int;
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	mediump vec4 unity_4LightAtten0;
					uniform 	mediump vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	mediump vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	mediump vec4 unity_SHAr;
					uniform 	mediump vec4 unity_SHAg;
					uniform 	mediump vec4 unity_SHAb;
					uniform 	mediump vec4 unity_SHBr;
					uniform 	mediump vec4 unity_SHBg;
					uniform 	mediump vec4 unity_SHBb;
					uniform 	mediump vec4 unity_SHC;
					uniform 	mediump vec3 unity_LightColor0;
					uniform 	mediump vec3 unity_LightColor1;
					uniform 	mediump vec3 unity_LightColor2;
					uniform 	mediump vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	mediump vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	lowp vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	lowp vec4 unity_AmbientSky;
					uniform 	lowp vec4 unity_AmbientEquator;
					uniform 	lowp vec4 unity_AmbientGround;
					uniform 	lowp vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	mediump vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					uniform lowp sampler2D _MainTex;
					in highp vec2 vs_TEXCOORD0;
					layout(location = 0) out lowp vec4 SV_Target0;
					highp vec4 t0;
					lowp vec4 t10_0;
					highp vec4 t1;
					lowp vec4 t10_1;
					lowp vec4 t10_2;
					void main()
					{
					    t0.xz = vec2(0.0, 0.0);
					    t0.yw = _MainTex_TexelSize.yy * vec2(-2.25, -0.447368413);
					    t0 = t0 + vs_TEXCOORD0.xyxy;
					    t10_1 = texture(_MainTex, t0.zw);
					    t10_0 = texture(_MainTex, t0.xy);
					    t10_1 = t10_1 * vec4(0.50666666, 0.50666666, 0.50666666, 0.50666666);
					    t10_0 = t10_0 * vec4(0.13333334, 0.13333334, 0.13333334, 0.13333334) + t10_1;
					    t1.xz = vec2(0.0, 0.0);
					    t1.yw = _MainTex_TexelSize.yy * vec2(1.30612242, 3.0);
					    t1 = t1 + vs_TEXCOORD0.xyxy;
					    t10_2 = texture(_MainTex, t1.xy);
					    t10_1 = texture(_MainTex, t1.zw);
					    t10_0 = t10_2 * vec4(0.326666653, 0.326666653, 0.326666653, 0.326666653) + t10_0;
					    SV_Target0 = t10_1 * vec4(0.0333333351, 0.0333333351, 0.0333333351, 0.0333333351) + t10_0;
					    return;
					}
					#endif"
}
SubProgram "glcore " {
"!!GLCore32
					#ifdef VERTEX
					#version 150
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_shader_bit_encoding : enable
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	vec4 unity_4LightAtten0;
					uniform 	vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	vec4 unity_SHAr;
					uniform 	vec4 unity_SHAg;
					uniform 	vec4 unity_SHAb;
					uniform 	vec4 unity_SHBr;
					uniform 	vec4 unity_SHBg;
					uniform 	vec4 unity_SHBb;
					uniform 	vec4 unity_SHC;
					uniform 	vec3 unity_LightColor0;
					uniform 	vec3 unity_LightColor1;
					uniform 	vec3 unity_LightColor2;
					uniform 	vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	vec4 unity_AmbientSky;
					uniform 	vec4 unity_AmbientEquator;
					uniform 	vec4 unity_AmbientGround;
					uniform 	vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					vec4 t0;
					void main()
					{
					    t0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    t0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + t0;
					    t0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + t0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + t0;
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    return;
					}
					#endif
					#ifdef FRAGMENT
					#version 150
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_shader_bit_encoding : enable
					uniform 	vec4 _Time;
					uniform 	vec4 _SinTime;
					uniform 	vec4 _CosTime;
					uniform 	vec4 unity_DeltaTime;
					uniform 	vec3 _WorldSpaceCameraPos;
					uniform 	vec4 _ProjectionParams;
					uniform 	vec4 _ScreenParams;
					uniform 	vec4 _ZBufferParams;
					uniform 	vec4 unity_OrthoParams;
					uniform 	vec4 unity_CameraWorldClipPlanes[6];
					uniform 	mat4 unity_CameraProjection;
					uniform 	mat4 unity_CameraInvProjection;
					uniform 	vec4 _WorldSpaceLightPos0;
					uniform 	vec4 _LightPositionRange;
					uniform 	vec4 unity_4LightPosX0;
					uniform 	vec4 unity_4LightPosY0;
					uniform 	vec4 unity_4LightPosZ0;
					uniform 	vec4 unity_4LightAtten0;
					uniform 	vec4 unity_LightColor[8];
					uniform 	vec4 unity_LightPosition[8];
					uniform 	vec4 unity_LightAtten[8];
					uniform 	vec4 unity_SpotDirection[8];
					uniform 	vec4 unity_SHAr;
					uniform 	vec4 unity_SHAg;
					uniform 	vec4 unity_SHAb;
					uniform 	vec4 unity_SHBr;
					uniform 	vec4 unity_SHBg;
					uniform 	vec4 unity_SHBb;
					uniform 	vec4 unity_SHC;
					uniform 	vec3 unity_LightColor0;
					uniform 	vec3 unity_LightColor1;
					uniform 	vec3 unity_LightColor2;
					uniform 	vec3 unity_LightColor3;
					uniform 	vec4 unity_ShadowSplitSpheres[4];
					uniform 	vec4 unity_ShadowSplitSqRadii;
					uniform 	vec4 unity_LightShadowBias;
					uniform 	vec4 _LightSplitsNear;
					uniform 	vec4 _LightSplitsFar;
					uniform 	mat4 unity_World2Shadow[4];
					uniform 	vec4 _LightShadowData;
					uniform 	vec4 unity_ShadowFadeCenterAndType;
					uniform 	mat4 glstate_matrix_mvp;
					uniform 	mat4 glstate_matrix_modelview0;
					uniform 	mat4 glstate_matrix_invtrans_modelview0;
					uniform 	mat4 _Object2World;
					uniform 	mat4 _World2Object;
					uniform 	vec4 unity_LODFade;
					uniform 	vec4 unity_WorldTransformParams;
					uniform 	mat4 glstate_matrix_transpose_modelview0;
					uniform 	mat4 glstate_matrix_projection;
					uniform 	vec4 glstate_lightmodel_ambient;
					uniform 	mat4 unity_MatrixV;
					uniform 	mat4 unity_MatrixVP;
					uniform 	vec4 unity_AmbientSky;
					uniform 	vec4 unity_AmbientEquator;
					uniform 	vec4 unity_AmbientGround;
					uniform 	vec4 unity_FogColor;
					uniform 	vec4 unity_FogParams;
					uniform 	vec4 unity_LightmapST;
					uniform 	vec4 unity_DynamicLightmapST;
					uniform 	vec4 unity_SpecCube0_BoxMax;
					uniform 	vec4 unity_SpecCube0_BoxMin;
					uniform 	vec4 unity_SpecCube0_ProbePosition;
					uniform 	vec4 unity_SpecCube0_HDR;
					uniform 	vec4 unity_SpecCube1_BoxMax;
					uniform 	vec4 unity_SpecCube1_BoxMin;
					uniform 	vec4 unity_SpecCube1_ProbePosition;
					uniform 	vec4 unity_SpecCube1_HDR;
					uniform 	vec4 _MainTex_TexelSize;
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 t0;
					mediump vec4 t16_0;
					lowp vec4 t10_0;
					vec4 t1;
					mediump vec4 t16_1;
					lowp vec4 t10_1;
					lowp vec4 t10_2;
					void main()
					{
					    t0.xz = vec2(0.0, 0.0);
					    t0.yw = _MainTex_TexelSize.yy * vec2(-2.25, -0.447368413);
					    t0 = t0 + vs_TEXCOORD0.xyxy;
					    t10_1 = texture(_MainTex, t0.zw);
					    t10_0 = texture(_MainTex, t0.xy);
					    t16_1 = t10_1 * vec4(0.50666666, 0.50666666, 0.50666666, 0.50666666);
					    t16_0 = t10_0 * vec4(0.13333334, 0.13333334, 0.13333334, 0.13333334) + t16_1;
					    t1.xz = vec2(0.0, 0.0);
					    t1.yw = _MainTex_TexelSize.yy * vec2(1.30612242, 3.0);
					    t1 = t1 + vs_TEXCOORD0.xyxy;
					    t10_2 = texture(_MainTex, t1.xy);
					    t10_1 = texture(_MainTex, t1.zw);
					    t16_0 = t10_2 * vec4(0.326666653, 0.326666653, 0.326666653, 0.326666653) + t16_0;
					    SV_Target0 = t10_1 * vec4(0.0333333351, 0.0333333351, 0.0333333351, 0.0333333351) + t16_0;
					    return;
					}
					#endif"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLLegacy"
}
SubProgram "d3d9 " {
"!!DX9PixelSM20
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float4 _MainTex_TexelSize;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _MainTex_TexelSize c0       1
					//   _MainTex           s0       1
					//
					
					    ps_2_0
					    def c1, 0.50666666, 0.13333334, 0.326666653, 0.0333333351
					    def c2, -2.25, -0.447368413, 1.30612242, 3
					    dcl t0.xy
					    dcl_2d s0
					    mov r0.x, t0.x
					    mov r1.w, c0.y
					    mad r0.y, r1.w, c2.y, t0.y
					    mov r1.x, t0.x
					    mad r1.y, r1.w, c2.x, t0.y
					    mov r2.x, t0.x
					    mad r2.y, r1.w, c2.z, t0.y
					    mov r3.x, t0.x
					    mad r3.y, r1.w, c2.w, t0.y
					    texld_pp r0, r0, s0
					    texld_pp r1, r1, s0
					    texld_pp r2, r2, s0
					    texld_pp r3, r3, s0
					    mul_pp r0, r0, c1.x
					    mad_pp r0, r1, c1.y, r0
					    mad_pp r0, r2, c1.z, r0
					    mad_pp r0, r3, c1.w, r0
					    mov_pp oC0, r0
					
					// approximately 18 instruction slots used (4 texture, 14 arithmetic)"
}
SubProgram "d3d11 " {
"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mov r0.xz, l(0,0,0,0)
					mul r0.yw, cb0[0].yyyy, l(0.000000, -2.250000, 0.000000, -0.447368)
					add r0.xyzw, r0.xyzw, v1.xyxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r1.xyzw, r1.xyzw, l(0.506667, 0.506667, 0.506667, 0.506667)
					mad r0.xyzw, r0.xyzw, l(0.133333, 0.133333, 0.133333, 0.133333), r1.xyzw
					mov r1.xz, l(0,0,0,0)
					mul r1.yw, cb0[0].yyyy, l(0.000000, 1.306122, 0.000000, 3.000000)
					add r1.xyzw, r1.xyzw, v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.326667, 0.326667, 0.326667, 0.326667), r0.xyzw
					mad o0.xyzw, r1.xyzw, l(0.033333, 0.033333, 0.033333, 0.033333), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles " {
"!!GLES"
}
SubProgram "d3d11_9x " {
"!!DX10Level9Pixel
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					//
					// Constant buffer to DX9 shader constant mappings:
					//
					// Target Reg Buffer  Start Reg # of Regs        Data Conversion
					// ---------- ------- --------- --------- ----------------------
					// c0         cb0             0         1  ( FLT, FLT, FLT, FLT)
					//
					//
					// Sampler/Resource to DX9 shader sampler mappings:
					//
					// Target Sampler Source Sampler  Source Resource
					// -------------- --------------- ----------------
					// s0             s0              t0               
					//
					//
					// Level9 shader bytecode:
					//
					    ps_2_0
					    def c1, 0.50666666, 0.13333334, 0.326666653, 0.0333333351
					    def c2, -2.25, -0.447368413, 1.30612242, 3
					    dcl t0.xy
					    dcl_2d s0
					    mov r0.x, t0.x
					    mov r1.w, c0.y
					    mad r0.y, r1.w, c2.y, t0.y
					    mov r1.x, t0.x
					    mad r1.y, r1.w, c2.x, t0.y
					    mov r2.x, t0.x
					    mad r2.y, r1.w, c2.z, t0.y
					    mov r3.x, t0.x
					    mad r3.y, r1.w, c2.w, t0.y
					    texld_pp r0, r0, s0
					    texld_pp r1, r1, s0
					    texld_pp r2, r2, s0
					    texld_pp r3, r3, s0
					    mul_pp r0, r0, c1.x
					    mad_pp r0, r1, c1.y, r0
					    mad_pp r0, r2, c1.z, r0
					    mad_pp r0, r3, c1.w, r0
					    mov_pp oC0, r0
					
					// approximately 18 instruction slots used (4 texture, 14 arithmetic)
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mov r0.xz, l(0,0,0,0)
					mul r0.yw, cb0[0].yyyy, l(0.000000, -2.250000, 0.000000, -0.447368)
					add r0.xyzw, r0.xyzw, v1.xyxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r1.xyzw, r1.xyzw, l(0.506667, 0.506667, 0.506667, 0.506667)
					mad r0.xyzw, r0.xyzw, l(0.133333, 0.133333, 0.133333, 0.133333), r1.xyzw
					mov r1.xz, l(0,0,0,0)
					mul r1.yw, cb0[0].yyyy, l(0.000000, 1.306122, 0.000000, 3.000000)
					add r1.xyzw, r1.xyzw, v1.xyxy
					sample r2.xyzw, r1.xyxx, t0.xyzw, s0
					sample r1.xyzw, r1.zwzz, t0.xyzw, s0
					mad r0.xyzw, r2.xyzw, l(0.326667, 0.326667, 0.326667, 0.326667), r0.xyzw
					mad o0.xyzw, r1.xyzw, l(0.033333, 0.033333, 0.033333, 0.033333), r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
}
SubProgram "gles3 " {
"!!GLES3"
}
SubProgram "glcore " {
"!!GLCore32"
}
}
 }
}
Fallback Off
}